#!/usr/bin/env bash
# Shared environment. Source this from every script.
#
# Homebrew's `mvn` runs on Java 26 by default, which Spark 3.5 rejects outright,
# so JAVA_HOME is pinned to the JDK 17 keg rather than left to the PATH.
# 17 also matches the JVM inside apache/spark:3.5.9-scala2.12-java17-ubuntu,
# so compiled bytecode and the cluster runtime agree.

JDK17_HOME="/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"
if [ ! -x "$JDK17_HOME/bin/javac" ]; then
    echo "error: JDK 17 not found at $JDK17_HOME" >&2
    echo "       install it with: brew install openjdk@17" >&2
    return 1 2>/dev/null || exit 1
fi
export JAVA_HOME="$JDK17_HOME"
export PATH="$JAVA_HOME/bin:$PATH"

# Resolve the project root without assuming which shell sourced this file.
# bash populates BASH_SOURCE; zsh does not, and `dirname ""` silently yields "."
# which resolves one directory too high. The eval keeps zsh-only syntax from
# being parsed by bash. The result is validated against a marker file, and falls
# back to the git toplevel, so a wrong answer fails loudly instead of pointing at
# a neighbouring directory.
_env_sh_dir() {
    if [ -n "${BASH_SOURCE:-}" ]; then
        (cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
    elif [ -n "${ZSH_VERSION:-}" ]; then
        (cd "$(dirname "$(eval 'printf %s "${(%):-%x}"')")" && pwd)
    fi
}

_script_dir="$(_env_sh_dir)"
PROJECT_ROOT=""
[ -n "$_script_dir" ] && PROJECT_ROOT="$(cd "$_script_dir/.." && pwd)"
if [ -z "$PROJECT_ROOT" ] || [ ! -f "$PROJECT_ROOT/docker/docker-compose.yml" ]; then
    PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
fi
if [ -z "$PROJECT_ROOT" ] || [ ! -f "$PROJECT_ROOT/docker/docker-compose.yml" ]; then
    echo "error: could not locate the project root." >&2
    echo "       run scripts from inside the repository." >&2
    return 1 2>/dev/null || exit 1
fi
unset _script_dir
export PROJECT_ROOT
export COMPOSE_FILE="$PROJECT_ROOT/docker/docker-compose.yml"
export ENV_FILE="$PROJECT_ROOT/.env"

# ---------------------------------------------------------------------------
# Credentials
#
# Loaded from .env, which is gitignored and generated by scripts/init-secrets.sh.
# Nothing here has a fallback value: a missing .env must stop the script rather
# than silently connect with a guessable default.
# ---------------------------------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
    echo "error: $ENV_FILE not found." >&2
    echo "       generate it with: ./scripts/init-secrets.sh" >&2
    return 1 2>/dev/null || exit 1
fi

set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

for required in POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD \
                CLICKHOUSE_DB CLICKHOUSE_USER CLICKHOUSE_PASSWORD; do
    # eval rather than ${!name}: indirect expansion is bash-only, and macOS
    # users source this from zsh where it is a syntax error.
    _value="$(eval "printf '%s' \"\${$required:-}\"")"
    if [ -z "$_value" ]; then
        echo "error: $required is not set in $ENV_FILE" >&2
        unset _value
        return 1 2>/dev/null || exit 1
    fi
    if [ "$_value" = "CHANGE_ME_GENERATE_WITH_INIT_SECRETS" ]; then
        echo "error: $required still holds the placeholder from .env.example." >&2
        echo "       run: ./scripts/init-secrets.sh --force" >&2
        unset _value
        return 1 2>/dev/null || exit 1
    fi
done
unset _value

# ---------------------------------------------------------------------------
# Non-secret endpoints
# ---------------------------------------------------------------------------
export PGHOST=localhost PGPORT=5432
export PGDATABASE="$POSTGRES_DB" PGUSER="$POSTGRES_USER"
export CH_HTTP=http://localhost:8123 CH_NATIVE=localhost:9000
export KAFKA_BOOTSTRAP_HOST=localhost:29092
export KAFKA_BOOTSTRAP_CLUSTER=kafka:9092
export SPARK_MASTER_URL=spark://spark-master:7077

# ---------------------------------------------------------------------------
# Helpers
#
# Passwords travel as environment variables, never as command-line arguments,
# so they do not appear in `ps` output or in shell history.
# ---------------------------------------------------------------------------

# docker compose, always with the explicit env file and compose file
dc() {
    docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
}

# psql inside the Postgres container
pg() {
    docker exec -e PGPASSWORD="$POSTGRES_PASSWORD" ap-postgres \
        psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" "$@"
}

# psql reading a script from stdin
pg_stdin() {
    docker exec -i -e PGPASSWORD="$POSTGRES_PASSWORD" ap-postgres \
        psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" "$@"
}

# clickhouse-client inside the ClickHouse container
ch() {
    docker exec -e CLICKHOUSE_USER="$CLICKHOUSE_USER" \
                -e CLICKHOUSE_PASSWORD="$CLICKHOUSE_PASSWORD" ap-clickhouse \
        clickhouse-client -d "$CLICKHOUSE_DB" "$@"
}

# JDBC URLs for Spark jobs. Built here so no job hardcodes a credential.
export PG_JDBC_URL="jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
export CH_JDBC_URL="jdbc:clickhouse://clickhouse:8123/${CLICKHOUSE_DB}"
