#!/usr/bin/env bash
#
# Generates docs/results/testing.md from ACTUAL test output.
#
# Generated, not hand-written, for the obvious reason: a hand-maintained status
# document drifts from reality the first time someone is in a hurry, and a stale
# "all green" is worse than no document at all.
#
#   ./scripts/generate-testing-report.sh
#
set -uo pipefail

source "$(dirname "${BASH_SOURCE[0]:-$0}")/env.sh"
cd "$PROJECT_ROOT"

REPORT=docs/results/testing.md
LOG=$(mktemp)

echo "Running the full gate to generate $REPORT ..."
./scripts/verify-all.sh > "$LOG" 2>&1
GATE_STATUS=$?

strip() { sed 's/\x1b\[[0-9;]*m//g' "$LOG"; }

# Scoped to the coverage-gate stage ONLY. The mutation stage re-runs the whole suite
# once per mutation and its output lands in the same log, so summing every "Tests run"
# line in the file reports the suite size multiplied by the number of mutations. The
# first version of this script did exactly that and claimed 1498 tests for a 749-test
# suite - an inflated number in a document whose entire purpose is being trustworthy.
TOTAL_TESTS=$(strip | sed -n '/^== tests + coverage gates ==/,/^== SQL constraint/p' | \
    grep -oE '^\[INFO\] Tests run: [0-9]+, Failures: [0-9]+, Errors: [0-9]+, Skipped: [0-9]+$' | \
    grep -oE 'Tests run: [0-9]+' | grep -oE '[0-9]+' | \
    awk '{s+=$1} END {print s+0}')
GUARANTEES=$(strip | grep -oE '[0-9]+ guarantee\(s\) verified' | grep -oE '^[0-9]+' | tail -1)
INSUFFICIENT=$(strip | grep -oE 'verified, [0-9]+ insufficient' | grep -oE '[0-9]+' | tail -1)
INVARIANTS=$(strip | grep -oE '[0-9]+ invariant\(s\) held' | grep -oE '^[0-9]+' | tail -1)
CONSTRAINTS=$(strip | grep -oE '[0-9]+ passed, [0-9]+ failed' | grep -oE '^[0-9]+' | tail -1)

mkdir -p docs/results
{
    echo "# Verification report"
    echo
    echo "_Generated by \`scripts/generate-testing-report.sh\` from actual test output._"
    echo "_Do not edit by hand: it will be overwritten, and a hand-maintained status"
    echo "document drifts from reality the first time someone is in a hurry._"
    echo
    echo "| | |"
    echo "|---|---|"
    echo "| Generated | $(date -u '+%Y-%m-%d %H:%M:%SZ') |"
    echo "| Git commit | \`$(git rev-parse --short HEAD 2>/dev/null || echo unknown)\` |"
    echo "| Branch | \`$(git branch --show-current 2>/dev/null || echo unknown)\` |"
    echo "| Java | $(java -version 2>&1 | head -1 | sed 's/"//g') |"
    echo "| Spark | $(grep -m1 '<spark.version>' pom.xml | sed -E 's/.*>(.*)<.*/\1/') |"
    echo "| Gate result | **$([ $GATE_STATUS -eq 0 ] && echo 'PASS' || echo 'FAIL')** |"
    echo
    echo "## Stages"
    echo
    echo "| Stage | Result |"
    echo "|---|---|"
    strip | grep -E '^  (PASS|FAIL)  ' | sed -E 's/^  (PASS|FAIL)  +(.*)$/| \2 | **\1** |/'
    echo
    echo "## Totals"
    echo
    echo "| Metric | Value |"
    echo "|---|---|"
    echo "| Tests executed | ${TOTAL_TESTS:-0} |"
    echo "| Mutation guarantees verified | ${GUARANTEES:-0} |"
    echo "| Guarantees insufficient | ${INSUFFICIENT:-0} |"
    echo "| Global invariants held | ${INVARIANTS:-0} |"
    echo "| SQL constraints rejected as expected | ${CONSTRAINTS:-0} |"
    echo
    echo "## What each suite defends"
    echo
    echo "| Claim | Suite | Tier |"
    echo "|---|---|---|"
    echo "| schema evolution | \`SchemaCompatibilityTest\`, \`SchemaProperties\`, \`SchemaRegistryIT\`, \`SilverSchemaEvolutionIT\` | 1 |"
    echo "| data-quality enforcement | \`DqRuleTest\`, \`DqEngineTest\`, \`SilverDqGateIT\` | 1 |"
    echo "| idempotent / restart-safe batch | \`PublishProtocolIT\`, \`BronzeIngestJobIT\` | 1 |"
    echo "| restart-safe streaming | \`StreamRecoveryIT\`, \`ReplacingMergeTreeIT\`, \`StreamEpochIT\` | 1 |"
    echo "| lineage / governance | \`LineageRecorderIT\`, \`E2EPipelineIT\`, \`verify-platform.sh\` | 1 |"
    echo "| performance measurement | \`BenchmarkStatisticsTest\`, \`BenchmarkReportTest\`, \`BenchmarkIT\` | 1 |"
    echo "| filesystem safety | \`StagingCleanerTest\` | 2 |"
    echo "| pipeline seams | \`E2EPipelineIT\` | 2 |"
    echo "| control-plane consistency | \`verify-platform.sh\` | 2 |"
    echo
    echo "## Mutation results"
    echo
    echo "Each line is a guarantee deliberately broken; the test defending it must go red."
    echo
    echo '```'
    strip | grep -E '^  (ok|FAIL|WARN) ' | sed 's/^  //'
    echo '```'
    echo
    echo "## Not covered"
    echo
    echo "Stated because the absence of a caveat reads as a claim."
    echo
    echo "- **No measured performance figure.** The benchmark harness is verified, but the"
    echo "  integration test runs on a 14-row fixture where fixed overhead dominates. A real"
    echo "  number requires \`./scripts/run-bench.sh\` against the full TLC dataset."
    echo "- **Tier 3 is not in this gate.** \`verify-hardening.sh\` runs nondeterminism detection,"
    echo "  high-volume property testing and resource pressure separately; it is slow and partly"
    echo "  probabilistic, and a release gate that takes an hour is one people route around."
    echo "- **\`StagingCleaner\`'s containment re-check is not a verified guarantee.** \`Files.walk\`"
    echo "  already does not follow symlinks, so no mutation of it can turn a test red. It is kept"
    echo "  as defence in depth and deliberately not claimed."
} > "$REPORT"

rm -f "$LOG"
echo "Wrote $REPORT"
[ $GATE_STATUS -eq 0 ] || echo "NOTE: the gate FAILED; the report records that faithfully."
exit $GATE_STATUS
