#!/usr/bin/env bash
#
# Generates .env with fresh random credentials.
#
# Refuses to overwrite an existing .env unless --force is passed, because the
# credentials are baked into the Postgres and ClickHouse data volumes at first
# initialization: regenerating them without also recreating those volumes leaves
# the stack unable to authenticate against its own databases.
#
#   ./scripts/init-secrets.sh          # create .env if absent
#   ./scripts/init-secrets.sh --force  # regenerate (then recreate volumes)
#
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
FORCE="${1:-}"

# 32 alphanumeric characters. Punctuation is excluded deliberately: JDBC and
# ClickHouse DSNs need it escaped, and the resulting failure looks like a
# connectivity problem rather than a quoting one.
generate_password() {
    LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32
}

if [ -f "$ENV_FILE" ] && [ "$FORCE" != "--force" ]; then
    echo "$ENV_FILE already exists; leaving it alone."
    echo "To rotate credentials: ./scripts/init-secrets.sh --force"
    echo "then recreate the data volumes, since the old passwords are baked into them:"
    echo "  docker compose --env-file .env -f docker/docker-compose.yml rm -sfv postgres clickhouse"
    echo "  docker volume rm analytics-platform_pgdata analytics-platform_chdata"
    exit 0
fi

umask 077   # created readable only by the owner, before any secret is written

cat > "$ENV_FILE" <<EOF
# Generated by scripts/init-secrets.sh. Gitignored: never commit this file.
# Rotating these requires recreating the Postgres and ClickHouse volumes,
# because the credentials are applied at database initialization.

POSTGRES_DB=platform
POSTGRES_USER=platform
POSTGRES_PASSWORD=$(generate_password)

CLICKHOUSE_DB=analytics
CLICKHOUSE_USER=platform
CLICKHOUSE_PASSWORD=$(generate_password)
EOF

chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE (mode 600)."
echo "Values are not echoed here on purpose; read the file directly if you need them."
